---
title: "Palmer Penguins"
author: "Nicola Rennie"
format: 
  dashboard:
    logo: images/logo.png
    theme: sketchy
    orientation: columns
    nav-buttons:
      - icon: github
        href: https://github.com/nrennie/ojs-project
engine: knitr
execute: 
  echo: false
  eval: true
---

## Row {width=60%}

```{ojs}
data = FileAttachment("data/penguins.csv").csv({ typed: true })

viewof bill_length_min = Inputs.range(
  [32, 50], 
  {value: 35, step: 1, label: "Bill length (min):"}
)
viewof islands = Inputs.checkbox(
  ["Torgersen", "Biscoe", "Dream"], 
  { value: ["Torgersen", "Biscoe"], 
    label: "Islands:"
  }
)

filtered = data.filter(function(penguin) {
  return bill_length_min < penguin.bill_length_mm &&
         islands.includes(penguin.island);
})

Plot.rectY(filtered, 
  Plot.binX(
    {y: "count"}, 
    {x: "body_mass_g", fill: "species", thresholds: 20}
  ))
  .plot({
    facet: {
      data: filtered,
      x: "sex",
      y: "species",
      marginRight: 80
    },
    marks: [
      Plot.frame(),
    ]
  }
)
```

## Row {width=40%}

```{r}
2 + 2
```

```{r}
3 + 3
```


